<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProgramStudiSeeder extends Seeder
{
    public function run()
    {
        DB::table('prodi')->insert([
            ['id_prodi' => 1001, 'nama_prodi' => 'Ilmu Hukum', 'strata' => 'S1', 'id_fakultas' => 10],
            ['id_prodi' => 1002, 'nama_prodi' => 'Hukum', 'strata' => 'S2', 'id_fakultas' => 10],
            ['id_prodi' => 1003, 'nama_prodi' => 'Kenotariatan', 'strata' => 'S2', 'id_fakultas' => 10],
            ['id_prodi' => 1004, 'nama_prodi' => 'Hukum', 'strata' => 'S3', 'id_fakultas' => 10],
            ['id_prodi' => 1101, 'nama_prodi' => 'Manajemen', 'strata' => 'S1', 'id_fakultas' => 11],
            ['id_prodi' => 1102, 'nama_prodi' => 'Ekonomi', 'strata' => 'S1', 'id_fakultas' => 11],
            ['id_prodi' => 1103, 'nama_prodi' => 'Akuntansi', 'strata' => 'S1', 'id_fakultas' => 11],
            ['id_prodi' => 1104, 'nama_prodi' => 'Ekonomi Islam', 'strata' => 'S1', 'id_fakultas' => 11],
            ['id_prodi' => 1105, 'nama_prodi' => 'Bisnis Digital', 'strata' => 'S1', 'id_fakultas' => 11],
            ['id_prodi' => 1106, 'nama_prodi' => 'Ekonomi', 'strata' => 'S2', 'id_fakultas' => 11],
            ['id_prodi' => 1107, 'nama_prodi' => 'Manajemen', 'strata' => 'S2', 'id_fakultas' => 11],
            ['id_prodi' => 1108, 'nama_prodi' => 'Akuntansi', 'strata' => 'S2', 'id_fakultas' => 11],
            ['id_prodi' => 1109, 'nama_prodi' => 'Ilmu Ekonomi', 'strata' => 'S3', 'id_fakultas' => 11],
            ['id_prodi' => 1201, 'nama_prodi' => 'Peternakan', 'strata' => 'S1', 'id_fakultas' => 12],
            ['id_prodi' => 1202, 'nama_prodi' => 'Agribisnis', 'strata' => 'S1', 'id_fakultas' => 12],
            ['id_prodi' => 1203, 'nama_prodi' => 'Teknologi Pangan', 'strata' => 'S1', 'id_fakultas' => 12],
            ['id_prodi' => 1204, 'nama_prodi' => 'Agroteknologi', 'strata' => 'S1', 'id_fakultas' => 12],
            ['id_prodi' => 1205, 'nama_prodi' => 'Peternakan', 'strata' => 'S2', 'id_fakultas' => 12],
            ['id_prodi' => 1206, 'nama_prodi' => 'Agribisnis', 'strata' => 'S2', 'id_fakultas' => 12],
            ['id_prodi' => 1207, 'nama_prodi' => 'Peternakan', 'strata' => 'S3', 'id_fakultas' => 12],
            ['id_prodi' => 1301, 'nama_prodi' => 'Psikologi', 'strata' => 'S1', 'id_fakultas' => 13],
            ['id_prodi' => 1302, 'nama_prodi' => 'Psikologi', 'strata' => 'S2', 'id_fakultas' => 13],
            ['id_prodi' => 1401, 'nama_prodi' => 'Sastra Indonesia', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1402, 'nama_prodi' => 'Sastra Inggris', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1403, 'nama_prodi' => 'Sejarah', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1404, 'nama_prodi' => 'Antropologi Sosial', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1405, 'nama_prodi' => 'Ilmu Perpustakaan', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1406, 'nama_prodi' => 'Bahasa dan Kebudayaan Jepang', 'strata' => 'S1', 'id_fakultas' => 14],
            ['id_prodi' => 1407, 'nama_prodi' => 'Linguistik', 'strata' => 'S2', 'id_fakultas' => 14],
            ['id_prodi' => 1408, 'nama_prodi' => 'Susastra', 'strata' => 'S2', 'id_fakultas' => 14],
            ['id_prodi' => 1409, 'nama_prodi' => 'Sejarah', 'strata' => 'S2', 'id_fakultas' => 14],
            ['id_prodi' => 1410, 'nama_prodi' => 'Sejarah', 'strata' => 'S3', 'id_fakultas' => 14],
            ['id_prodi' => 1501, 'nama_prodi' => 'Ilmu Kelautan', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1502, 'nama_prodi' => 'Manajemen Sumber Daya Perairan', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1503, 'nama_prodi' => 'Akuakultur', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1504, 'nama_prodi' => 'Perikanan Tangkap', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1505, 'nama_prodi' => 'Oseanografi', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1506, 'nama_prodi' => 'Teknologi Hasil Perikanan', 'strata' => 'S1', 'id_fakultas' => 15],
            ['id_prodi' => 1507, 'nama_prodi' => 'Ilmu Kelautan', 'strata' => 'S2', 'id_fakultas' => 15],
            ['id_prodi' => 1508, 'nama_prodi' => 'Manajemen Sumber Daya Perairan', 'strata' => 'S2', 'id_fakultas' => 15],
            ['id_prodi' => 1509, 'nama_prodi' => 'Ilmu Kelautan', 'strata' => 'S3', 'id_fakultas' => 15],
            ['id_prodi' => 1510, 'nama_prodi' => 'Manajemen Sumber Daya Perairan', 'strata' => 'S3', 'id_fakultas' => 15],
            ['id_prodi' => 1601, 'nama_prodi' => 'Teknik Sipil', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1602, 'nama_prodi' => 'Teknik Mesin', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1603, 'nama_prodi' => 'Teknik Elektro', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1604, 'nama_prodi' => 'Teknik Kimia', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1605, 'nama_prodi' => 'Arsitektur', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1606, 'nama_prodi' => 'Teknik Lingkungan', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1607, 'nama_prodi' => 'Perencanaan Wilayah dan Kota', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1608, 'nama_prodi' => 'Teknik Perkapalan', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1609, 'nama_prodi' => 'Teknik Industri', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1610, 'nama_prodi' => 'Teknik Geologi', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1611, 'nama_prodi' => 'Teknik Geodesi', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1612, 'nama_prodi' => 'Teknik Komputer', 'strata' => 'S1', 'id_fakultas' => 16],
            ['id_prodi' => 1613, 'nama_prodi' => 'Teknik Sipil', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1614, 'nama_prodi' => 'Teknik Mesin', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1615, 'nama_prodi' => 'Teknik Kimia', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1616, 'nama_prodi' => 'Teknik Arsitektur', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1617, 'nama_prodi' => 'Teknik Elektro', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1618, 'nama_prodi' => 'Perencanaan Wilayah dan Kota', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1619, 'nama_prodi' => 'Teknik dan Manajemen Industri', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1620, 'nama_prodi' => 'Teknik Lingkungan', 'strata' => 'S2', 'id_fakultas' => 16],
            ['id_prodi' => 1621, 'nama_prodi' => 'Ilmu Teknik Sipil', 'strata' => 'S3', 'id_fakultas' => 16],
            ['id_prodi' => 1622, 'nama_prodi' => 'Ilmu Arsitektur dan Perkotaan', 'strata' => 'S3', 'id_fakultas' => 16],
            ['id_prodi' => 1623, 'nama_prodi' => 'Teknik Kimia', 'strata' => 'S3', 'id_fakultas' => 16],
            ['id_prodi' => 1624, 'nama_prodi' => 'Teknik Mesin', 'strata' => 'S3', 'id_fakultas' => 16],
            ['id_prodi' => 1625, 'nama_prodi' => 'Perencanaan Wilayah dan Kota', 'strata' => 'S3', 'id_fakultas' => 16],
            ['id_prodi' => 1701, 'nama_prodi' => 'Administrasi Publik', 'strata' => 'S1', 'id_fakultas' => 17],
            ['id_prodi' => 1702, 'nama_prodi' => 'Ilmu Komunikasi', 'strata' => 'S1', 'id_fakultas' => 17],
            ['id_prodi' => 1703, 'nama_prodi' => 'Ilmu Pemerintahan', 'strata' => 'S1', 'id_fakultas' => 17],
            ['id_prodi' => 1704, 'nama_prodi' => 'Hubungan Internasional', 'strata' => 'S1', 'id_fakultas' => 17],
            ['id_prodi' => 1705, 'nama_prodi' => 'Administrasi Bisnis', 'strata' => 'S1', 'id_fakultas' => 17],
            ['id_prodi' => 1706, 'nama_prodi' => 'Administrasi Bisnis', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1707, 'nama_prodi' => 'Konsentrasi Komunikasi Strategis', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1708, 'nama_prodi' => 'Konsentrasi Media, Budaya dan Masyarakat', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1709, 'nama_prodi' => 'Ilmu Komunikasi', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1710, 'nama_prodi' => 'Ilmu Politik', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1711, 'nama_prodi' => 'Administrasi Publik', 'strata' => 'S2', 'id_fakultas' => 17],
            ['id_prodi' => 1712, 'nama_prodi' => 'Ilmu Sosial', 'strata' => 'S3', 'id_fakultas' => 17],
            ['id_prodi' => 1713, 'nama_prodi' => 'Administrasi Publik', 'strata' => 'S3', 'id_fakultas' => 17],
            ['id_prodi' => 1801, 'nama_prodi' => 'Kedokteran', 'strata' => 'S1', 'id_fakultas' => 18],
            ['id_prodi' => 1802, 'nama_prodi' => 'Kedokteran Gigi', 'strata' => 'S1', 'id_fakultas' => 18],
            ['id_prodi' => 1803, 'nama_prodi' => 'Keperawatan', 'strata' => 'S1', 'id_fakultas' => 18],
            ['id_prodi' => 1804, 'nama_prodi' => 'Farmasi', 'strata' => 'S1', 'id_fakultas' => 18],
            ['id_prodi' => 1805, 'nama_prodi' => 'Gizi', 'strata' => 'S1', 'id_fakultas' => 18],
            ['id_prodi' => 1806, 'nama_prodi' => 'Keperawatan', 'strata' => 'S2', 'id_fakultas' => 18],
            ['id_prodi' => 1807, 'nama_prodi' => 'Ilmu Gizi', 'strata' => 'S3', 'id_fakultas' => 18],
            ['id_prodi' => 1808, 'nama_prodi' => 'Ilmu Biomedis', 'strata' => 'S3', 'id_fakultas' => 18],
            ['id_prodi' => 1809, 'nama_prodi' => 'Ilmu Kedokteran dan Kesehatan', 'strata' => 'S3', 'id_fakultas' => 18],
            ['id_prodi' => 1901, 'nama_prodi' => 'Kesehatan Masyarakat', 'strata' => 'S1', 'id_fakultas' => 19],
            ['id_prodi' => 1902, 'nama_prodi' => 'Keselamatan dan Kesehatan Kerja(K3)', 'strata' => 'S1', 'id_fakultas' => 19],
            ['id_prodi' => 1903, 'nama_prodi' => 'Kesehatan Masyarakat', 'strata' => 'S2', 'id_fakultas' => 19],
            ['id_prodi' => 1904, 'nama_prodi' => 'Epidemiologi', 'strata' => 'S2', 'id_fakultas' => 19],
            ['id_prodi' => 1905, 'nama_prodi' => 'Promosi Kesehatan', 'strata' => 'S2', 'id_fakultas' => 19],
            ['id_prodi' => 1906, 'nama_prodi' => 'Kesehatan Lingkungan', 'strata' => 'S2', 'id_fakultas' => 19],
            ['id_prodi' => 1907, 'nama_prodi' => 'Kesehatan Masyarakat', 'strata' => 'S3', 'id_fakultas' => 19],
            ['id_prodi' => 2001, 'nama_prodi' => 'Matematika', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2002, 'nama_prodi' => 'Fisika', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2003, 'nama_prodi' => 'Kimia', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2004, 'nama_prodi' => 'Biologi', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2005, 'nama_prodi' => 'Statistika', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2006, 'nama_prodi' => 'Bioteknologi', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2007, 'nama_prodi' => 'Informatika', 'strata' => 'S1', 'id_fakultas' => 20],
            ['id_prodi' => 2008, 'nama_prodi' => 'Matematika', 'strata' => 'S2', 'id_fakultas' => 20],
            ['id_prodi' => 2009, 'nama_prodi' => 'Fisika', 'strata' => 'S2', 'id_fakultas' => 20],
            ['id_prodi' => 2010, 'nama_prodi' => 'Kimia', 'strata' => 'S2', 'id_fakultas' => 20],
            ['id_prodi' => 2011, 'nama_prodi' => 'Biologi', 'strata' => 'S2', 'id_fakultas' => 20],
            ['id_prodi' => 2012, 'nama_prodi' => 'Fisikawan Medik', 'strata' => 'S2', 'id_fakultas' => 20],
            ['id_prodi' => 2013, 'nama_prodi' => 'Sains Matematika/Matematika dan Ilmu Pengetahuan Alam(MIPA)', 'strata' => 'S3', 'id_fakultas' => 20],
            ['id_prodi' => 2101, 'nama_prodi' => 'Teknologi Rekayasa Kimia Industri', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2102, 'nama_prodi' => 'Teknologi Rekayasa Otomasi', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2103, 'nama_prodi' => 'Rekayasa Perancangan Mekanik', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2104, 'nama_prodi' => 'Teknologi Rekayasa Konstruksi Perkapalan', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2105, 'nama_prodi' => 'Teknologi Listrik Industri', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2106, 'nama_prodi' => 'Perencanaan Tata Ruang dan Pertanahan', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2107, 'nama_prodi' => 'Teknik Infrastruktur Sipil dan Perancangan Arsitektur', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2108, 'nama_prodi' => 'Akuntansi Perpajakan', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2109, 'nama_prodi' => 'Manajemen dan Administrasi Logistik', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2110, 'nama_prodi' => 'Bahasa Asing Terapan', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2111, 'nama_prodi' => 'Informasi dan Humas', 'strata' => 'D4', 'id_fakultas' => 21],
            ['id_prodi' => 2201, 'nama_prodi' => 'Ilmu Lingkungan', 'strata' => 'S2', 'id_fakultas' => 22],
            ['id_prodi' => 2202, 'nama_prodi' => 'Sistem Informasi', 'strata' => 'S2', 'id_fakultas' => 22],
            ['id_prodi' => 2203, 'nama_prodi' => 'Energi', 'strata' => 'S2', 'id_fakultas' => 22],
            ['id_prodi' => 2204, 'nama_prodi' => 'Ilmu Lingkungan', 'strata' => 'S3', 'id_fakultas' => 22],
            ['id_prodi' => 2205, 'nama_prodi' => 'Sistem Informasi', 'strata' => 'S3', 'id_fakultas' => 22],
        ]);
    }
}
